name: Validacao & Linter

on:
  pull_request:
    branches: ["master"]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Ruby
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Verificar vulnerabilidades nas dependências
        run: |
          gem install bundler-audit --quiet
          bundle-audit update
          bundle-audit check

      - name: Validar arquivos YAML
        run: |
          gem install yaml-lint --quiet
          yaml-lint _config.yml _data/navigation.yml

      - name: Validar arquivos Markdown
        uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          globs: |
            _pages/**/*.md
            README.md

      - name: Compilar Jekyll (modo estrito)
        run: bundle exec jekyll build --strict_front_matter
